version: '3.8'

services:
  auth:
    build: ./auth
    env_file:
      - ./auth/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network

  product:
    build: ./product
    env_file:
      - ./product/.env
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - auth
    networks:
      - app-network

  order:
    build: ./order
    env_file:
      - ./order/.env
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - auth
      - product
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mymongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
